### ISSUE TITLE
提交一个遇到的问题

### ISSUE THREAD

**Issue by AhFeil** [Geralt-TYH/obsidian-zhihu-crawler#1]
Traceback (most recent call last):
  File "C:\Users\AhFei\main.py", line 211, in <module>
    with open("./剪藏/" + title + ".md", "w", encoding='utf-8') as md_file:
OSError: [Errno 22] Invalid argument: './剪藏/不小心用kms激活了win10，怎么恢复正版?.md'

**Comment by lin0kin** [comment]
> Traceback (most recent call last): File "C:\Users\AhFei\main.py", line 211, in with open("./剪藏/" + title + ".md", "w", encoding='utf-8') as md_file: OSError: [Errno 22] Invalid argument: './剪藏/不小心用kms激活了win10，怎么恢复正版?.md'

我也遇到了, 应该是win不允许某些英文字符作为文件名

**Comment by Geralt-TYH** [comment]
> Traceback (most recent call last): File "C:\Users\AhFei\main.py", line 211, in with open("./剪藏/" + title + ".md", "w", encoding='utf-8') as md_file: OSError: [Errno 22] Invalid argument: './剪藏/不小心用kms激活了win10，怎么恢复正版?.md'

 @AhFeil @lin0kin 谢谢反馈，windows的文件命名规则不能包含**特殊字符**，这个问题下个版本修复
